version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: gatbsy test
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: gatsby clean
            - run: gatsby build
workflows:
    build-and-test:
      jobs:
        - build-and-test
    build-and-deploy:
      jobs:
        - build-and-deploy